"""empty message

Revision ID: 767d3abd49cc
Revises: ffaca3d428a3
Create Date: 2021-01-23 11:50:16.000241

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '767d3abd49cc'
down_revision = 'ffaca3d428a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    now=datetime.now()
    op.add_column('artist', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.execute('UPDATE artist SET create_time=CURRENT_TIMESTAMP WHERE create_time IS NULL')
    op.alter_column('artist', 'create_time', nullable=False)
    op.add_column('venue', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.execute('UPDATE venue SET create_time=CURRENT_TIMESTAMP WHERE create_time IS NULL')
    op.alter_column('venue', 'create_time', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'create_time')
    op.drop_column('artist', 'create_time')
    # ### end Alembic commands ###
